# Generated by Django 3.2.23 on 2023-12-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0001_initial'),
        ('DataManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsdata',
            name='Pfd_company_Id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.businessregister_details'),
        ),
        migrations.AlterField(
            model_name='databank',
            name='current_status',
            field=models.CharField(default='No updation', max_length=150),
        ),
    ]
