# Generated by Django 3.2.23 on 2023-12-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration_Login', '0001_initial'),
        ('DM_Head', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads_assignto_tc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Reason', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Assign_Date', models.DateField(auto_now=True, null=True)),
                ('Update_Date', models.DateField(blank=True, default='', max_length=255, null=True)),
                ('Next_update_date', models.DateField(blank=True, max_length=255, null=True)),
                ('Update_Action', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('TC_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details')),
                ('client_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.clientregister')),
                ('leadId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.leads')),
            ],
        ),
        migrations.CreateModel(
            name='Waste_Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(default=0)),
                ('TC_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details')),
                ('client_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.clientregister')),
                ('leadId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.leads')),
            ],
        ),
        migrations.CreateModel(
            name='Leads_Call_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Record', models.FileField(blank=True, default='', null=True, upload_to='record')),
                ('Leads_assignto_tc_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Telecaller.leads_assignto_tc')),
            ],
        ),
    ]
