# Generated by Django 3.2.23 on 2023-12-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataManager', '0002_auto_20231207_1100'),
        ('DM_Head', '0002_leads_lead_category_id'),
        ('Telecaller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads_assignto_tc',
            name='dataBank_ID',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DataManager.databank'),
        ),
        migrations.AddField(
            model_name='leads_call_record',
            name='leadId',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.leads'),
        ),
        migrations.AddField(
            model_name='leads_call_record',
            name='record_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leads_call_record',
            name='record_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='waste_leads',
            name='dbId',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DataManager.databank'),
        ),
        migrations.AddField(
            model_name='waste_leads',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='waste_leads',
            name='waste_marked_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads_assignto_tc',
            name='Assign_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads_assignto_tc',
            name='Next_update_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leads_assignto_tc',
            name='Update_Date',
            field=models.DateField(null=True),
        ),
    ]
