# Generated by Django 3.2.23 on 2024-01-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telecaller', '0002_auto_20231207_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_leads',
            name='confirmation',
            field=models.IntegerField(default=0),
        ),
    ]
