# Generated by Django 5.0.1 on 2024-02-16 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telecaller', '0003_waste_leads_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_leads',
            name='assignto_tc_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Telecaller.leads_assignto_tc'),
        ),
    ]
