# Generated by Django 5.0.1 on 2024-03-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telecaller', '0004_waste_leads_assignto_tc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads_assignto_tc',
            name='Allocate_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
