# Generated by Django 3.2.23 on 2023-12-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='lead_category_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.leadcategory_register'),
        ),
    ]
