# Generated by Django 3.2.23 on 2023-12-11 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0002_leads_lead_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcateogry_assign',
            name='ta_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.taskassign'),
        ),
    ]
