# Generated by Django 3.2.23 on 2023-12-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0003_leadcateogry_assign_ta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='previos_allocation_details',
            name='newallocation_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
