# Generated by Django 5.0.1 on 2024-04-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0004_previos_allocation_details_newallocation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='lead_incomplete_status',
            field=models.IntegerField(default=0),
        ),
    ]
