# Generated by Django 5.0.1 on 2024-04-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0005_leads_lead_incomplete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='repeated_status',
            field=models.IntegerField(default=0),
        ),
    ]
