# Generated by Django 5.0.1 on 2024-04-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0006_leads_repeated_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='waste_data_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
