# Generated by Django 5.0.1 on 2024-04-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0007_leads_waste_data_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_add_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
