# Generated by Django 5.0.1 on 2024-04-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0008_alter_leads_lead_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_transfer_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
